function data = importsinglefile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  CELLSLIPIDOMICSPOSLOG2 = IMPORTFILE1(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  CELLSLIPIDOMICSPOSLOG2 = IMPORTFILE1(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  cellslipidomicsposlog2 = importfile1("C:\Users\paavo\Tiedostot\PARKINSONS\PDproj\celldata\clean\cellslipidomicspos_log2.csv", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Mar-2023 14:38:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 48);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "aSYN", "aSYN1", "aSYN2", "aSYN3", "aSYN4", "aSYN5", "aSYN6", "aSYN7", "aSYN8", "aSYN9", "comb", "comb1", "comb2", "comb3", "comb4", "comb5", "comb6", "comb7", "comb8", "comb9", "INFg", "INFg1", "INFg2", "INFg3", "INFg4", "INFg5", "INFg6", "INFg7", "INFg8", "INFg9", "UT", "UT1", "UT2", "UT3", "UT4", "UT5", "UT6", "UT7", "UT8", "UT9"];
opts.VariableTypes = ["string", "categorical", "double", "double", "double", "double", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName7"], "EmptyFieldRule", "auto");
%opts = setvaropts(opts, "VarName8", "TrimNonNumeric", true);
%opts = setvaropts(opts, "VarName8", "ThousandsSeparator", ",");

% Import the data
data = readtable(filename, opts);

end